services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: taskhub-backend
    environment:
      - DB_USER=app_user
      - DB_HOST=localhost
      - DB_PASSWORD=secure_password
      - CONFIG_PATH=/app/config.yaml
      - PORT=8080
    ports:
      - "8080:8080"
    volumes:
      - backend_data:/app/data
      - ./backend/config.yaml:/app/config.yaml:ro
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: taskhub-frontend
    environment:
      - REACT_APP_API_URL=http://backend:8080/api/v1
    ports:
      - "3000:3000"
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  backend_data:
    driver: local

networks:
  app-network:
    driver: bridge