# This file is maintained automatically by "flux bootstrap github".
# See the toolkit.fluxcd.io/syncDisabled annotation below to disable auto-deployment.
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: main
  secretRef:
    name: flux-system
  url: ssh://git@github.com/jovanvuleta/taskhub
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./flux/clusters/staging
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system