app:
  name: "taskhub-backend"
  version: "1.0.0"
  port: 8080
  environment: "production"

database:
  type: "sqlite"
  path: "./data.db"
  max_connections: 200
  timeout: 30

logging:
  level: "info"
  format: "json"

security:
  cors_enabled: true
  cors_origins: 
    - "https://taskhub.dev"
    - "https://www.taskhub.dev"