apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: taskhub-base
  annotations:
    config.kubernetes.io/local-config: "true"

resources:
- namespace.yaml
- configmap.yaml
- secret.yaml
- pvc.yaml
- backend-deployment.yaml
- backend-service.yaml
- frontend-deployment.yaml
- frontend-service.yaml
- ingress.yaml
- network-policy.yaml
- pod-disruption-budget.yaml

labels:
- pairs:
    app.kubernetes.io/instance: taskhub
    app.kubernetes.io/managed-by: kustomize

images:
- name: taskhub-backend
  newName: ghcr.io/jovanvuleta/taskhub-backend # {"$imagepolicy": "flux-system:taskhub-backend-policy"}
  newTag: v0.0.1 # {"$imagepolicy": "flux-system:taskhub-backend-policy:tag"}
- name: taskhub-frontend
  newName: ghcr.io/jovanvuleta/taskhub-frontend # {"$imagepolicy": "flux-system:taskhub-frontend-policy"}
  newTag: v0.0.1 # {"$imagepolicy": "flux-system:taskhub-frontend-policy:tag"}