---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sqlite-pvc
  labels:
    app.kubernetes.io/name: sqlite-storage
    app.kubernetes.io/component: database
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: standard